In [1]:
import pandas as pd

In [36]:
df = pd.read_csv('../../datasets/Dataset_credit_scoring.tsv', sep='\t')

In [4]:
df.head()

Occupation  Age  Loan_Salary_ratio  Outcome
0    Industrial   34               2.96    Repay
1  Professional   41               4.64  Default
2  Professional   36               3.22  Default
3  Professional   41               3.11  Default
4    Industrial   48               3.80  Default

In [5]:
df.head(8)

Occupation  Age  Loan_Salary_ratio  Outcome
0    Industrial   34               2.96    Repay
1  Professional   41               4.64  Default
2  Professional   36               3.22  Default
3  Professional   41               3.11  Default
4    Industrial   48               3.80  Default
5    Industrial   61               2.53    Repay
6  Professional   37               1.50    Repay
7  Professional   40               1.93    Repay

In [6]:
df.tail()

Occupation  Age  Loan_Salary_ratio  Outcome
5    Industrial   61               2.53    Repay
6  Professional   37               1.50    Repay
7  Professional   40               1.93    Repay
8    Industrial   33               5.25  Default
9    Industrial   32               4.15  Default

In [7]:
df.columns

Index(['Occupation', 'Age', 'Loan_Salary_ratio', 'Outcome'], dtype='object')

In [8]:
df.describe()

Age  Loan_Salary_ratio
count  10.000000           10.00000
mean   40.300000            3.30900
std     8.692909            1.17557
min    32.000000            1.50000
25%    34.500000            2.63750
50%    38.500000            3.16500
75%    41.000000            4.06250
max    61.000000            5.25000

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Occupation         10 non-null     object 
 1   Age                10 non-null     int64  
 2   Loan_Salary_ratio  10 non-null     float64
 3   Outcome            10 non-null     object 
dtypes: float64(1), int64(1), object(2)
memory usage: 448.0+ bytes


In [10]:
df.columns

Index(['Occupation', 'Age', 'Loan_Salary_ratio', 'Outcome'], dtype='object')

In [13]:
df.head()

Occupation  Age  Loan_Salary_ratio  Outcome
0    Industrial   34               2.96    Repay
1  Professional   41               4.64  Default
2  Professional   36               3.22  Default
3  Professional   41               3.11  Default
4    Industrial   48               3.80  Default

In [15]:
df['Outcome']

0      Repay
1    Default
2    Default
3    Default
4    Default
5      Repay
6      Repay
7      Repay
8    Default
9    Default
Name: Outcome, dtype: object

In [16]:
df['Age']

0    34
1    41
2    36
3    41
4    48
5    61
6    37
7    40
8    33
9    32
Name: Age, dtype: int64

In [17]:
df['Age'].unique()

array([34, 41, 36, 48, 61, 37, 40, 33, 32])

In [18]:
df['Age'].nunique()

9

In [20]:
df['Age'].max()

61

In [21]:
df['Age'].min()

32

In [23]:
df['Loan_Salary_ratio'].unique()

array([2.96, 4.64, 3.22, 3.11, 3.8 , 2.53, 1.5 , 1.93, 5.25, 4.15])

In [25]:
df['Occupation'].value_counts()

Industrial      5
Professional    5
Name: Occupation, dtype: int64

In [28]:
df['Age'] > 40

0    False
1     True
2    False
3     True
4     True
5     True
6    False
7    False
8    False
9    False
Name: Age, dtype: bool

In [27]:
df[df['Age'] > 40]

Occupation  Age  Loan_Salary_ratio  Outcome
1  Professional   41               4.64  Default
3  Professional   41               3.11  Default
4    Industrial   48               3.80  Default
5    Industrial   61               2.53    Repay

In [29]:
df[df['Product'] == 'Tartuffo']

KeyError: 'Product'

In [37]:
df.head() 

Occupation  Age  Loan_Salary_ratio  Outcome
0    Industrial   34               2.96    Repay
1  Professional   41               4.64  Default
2  Professional   36               3.22  Default
3  Professional   41               3.11  Default
4    Industrial   48               3.80  Default

In [40]:
new_df = df.drop(['Outcome'], axis=1)

In [42]:
new_df.head()

Occupation  Age  Loan_Salary_ratio
0    Industrial   34               2.96
1  Professional   41               4.64
2  Professional   36               3.22
3  Professional   41               3.11
4    Industrial   48               3.80

In [43]:
new_df2 = df[['Occupation', 'Age', 'Loan_Salary_ratio']]

In [46]:
new_df2.head()

Occupation  Age  Loan_Salary_ratio
0    Industrial   34               2.96
1  Professional   41               4.64
2  Professional   36               3.22
3  Professional   41               3.11
4    Industrial   48               3.80

In [51]:
df.columns

Index(['Occupation', 'Age', 'Loan_Salary_ratio', 'Outcome'], dtype='object')

In [52]:
df.columns[:-1]

Index(['Occupation', 'Age', 'Loan_Salary_ratio'], dtype='object')

In [50]:
df[df.columns[:-1]]

Occupation  Age  Loan_Salary_ratio
0    Industrial   34               2.96
1  Professional   41               4.64
2  Professional   36               3.22
3  Professional   41               3.11
4    Industrial   48               3.80
5    Industrial   61               2.53
6  Professional   37               1.50
7  Professional   40               1.93
8    Industrial   33               5.25
9    Industrial   32               4.15

In [53]:
df.columns

Index(['Occupation', 'Age', 'Loan_Salary_ratio', 'Outcome'], dtype='object')

In [54]:
df.columns[1]

'Age'

In [55]:
df.columns[2]

'Loan_Salary_ratio'

In [57]:
df.index

RangeIndex(start=0, stop=10, step=1)

In [58]:
df.iloc[0]

Occupation           Industrial
Age                          34
Loan_Salary_ratio          2.96
Outcome                   Repay
Name: 0, dtype: object

In [61]:
df.head()

Occupation  Age  Loan_Salary_ratio  Outcome
0    Industrial   34               2.96    Repay
1  Professional   41               4.64  Default
2  Professional   36               3.22  Default
3  Professional   41               3.11  Default
4    Industrial   48               3.80  Default

In [62]:
df['corrected_age'] = df['Age'] + 2

In [63]:
df.head()

Occupation  Age  Loan_Salary_ratio  Outcome  corrected_age
0    Industrial   34               2.96    Repay             36
1  Professional   41               4.64  Default             43
2  Professional   36               3.22  Default             38
3  Professional   41               3.11  Default             43
4    Industrial   48               3.80  Default             50

In [64]:
df.drop(['Age'], axis=1)

Occupation  Loan_Salary_ratio  Outcome  corrected_age
0    Industrial               2.96    Repay             36
1  Professional               4.64  Default             43
2  Professional               3.22  Default             38
3  Professional               3.11  Default             43
4    Industrial               3.80  Default             50
5    Industrial               2.53    Repay             63
6  Professional               1.50    Repay             39
7  Professional               1.93    Repay             42
8    Industrial               5.25  Default             35
9    Industrial               4.15  Default             34

In [73]:
df.groupby(['Outcome'])['Loan_Salary_ratio'].mean()

Outcome
Default    4.028333
Repay      2.230000
Name: Loan_Salary_ratio, dtype: float64

In [76]:
df.groupby(['Outcome'])['Loan_Salary_ratio'].describe()

count      mean       std   min     25%    50%     75%   max
Outcome                                                              
Default    6.0  4.028333  0.828285  3.11  3.3650  3.975  4.5175  5.25
Repay      4.0  2.230000  0.644412  1.50  1.8225  2.230  2.6375  2.96

In [79]:
new_df = pd.DataFrame(df.groupby(['Outcome'])['Loan_Salary_ratio'].mean())

In [80]:
new_df

Loan_Salary_ratio
Outcome                   
Default           4.028333
Repay             2.230000

In [81]:
new_df['min'] = df.groupby(['Outcome'])['Loan_Salary_ratio'].min()

In [82]:
new_df

Loan_Salary_ratio   min
Outcome                         
Default           4.028333  3.11
Repay             2.230000  1.50

In [83]:
df.head()

Occupation  Age  Loan_Salary_ratio  Outcome  corrected_age
0    Industrial   34               2.96    Repay             36
1  Professional   41               4.64  Default             43
2  Professional   36               3.22  Default             38
3  Professional   41               3.11  Default             43
4    Industrial   48               3.80  Default             50

In [84]:
import numpy as np

In [87]:
df[['Age', 'corrected_age']].values

array([[34, 36],
       [41, 43],
       [36, 38],
       [41, 43],
       [48, 50],
       [61, 63],
       [37, 39],
       [40, 42],
       [33, 35],
       [32, 34]])